server:
  port: 8084
  servlet:
    context-path: /api/v1
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

spring:
  application:
    name: helpmeiud
  datasource:
    url: jdbc:mysql://localhost:3306/helpme_iud
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update #validate, create-drop,...
    show-sql: true

  mail:
    from: noreply@iudigital.edu.co
    host: smtp.gmail.com
    port: 587
    username: julio.martinez@iudigital.edu.co
    password: tu_contrase√±a
    properties:
      protocol: smtp
      auth: true
      starttls:
        enabled: true
